
services:
  client:
    build:
      context: ./Sandbox.Client
      args:
        API_URL: http://api/api
    ports:
      - "4200:80"

  api:
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./Sandbox.Web/appsettings.Production.json:/app/appsettings.Production.json
      - ./Sandbox.Web/appsettings.json:/app/appsettings.json
